"""add scores column to commission_evaluations

Revision ID: 3199198e597b
Revises: ada527385465
Create Date: 2026-03-21 02:40:54.521626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3199198e597b'
down_revision: Union[str, Sequence[str], None] = 'ada527385465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission_evaluations', sa.Column('scores', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commission_evaluations', 'scores')
    # ### end Alembic commands ###
