"""add role_id to user table

Revision ID: 3f590191fdab
Revises: 1aa4a420b438
Create Date: 2026-03-25 17:13:19.179760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f590191fdab'
down_revision: Union[str, Sequence[str], None] = '1aa4a420b438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_reset')
    op.drop_index(op.f('idx_presentation_schedule_date'), table_name='presentation_schedule')
    op.drop_index(op.f('idx_presentation_schedule_project'), table_name='presentation_schedule')
    op.alter_column('project', 'max_participants',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.execute("ALTER TABLE project ALTER COLUMN max_participants TYPE INTEGER USING max_participants::integer")
    op.create_index(op.f('idx_presentation_schedule_project'), 'presentation_schedule', ['project_id'], unique=False)
    op.create_index(op.f('idx_presentation_schedule_date'), 'presentation_schedule', ['presentation_date'], unique=False)
    op.create_table('password_reset',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('password_reset_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_pkey')),
    sa.UniqueConstraint('token', name=op.f('password_reset_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
