"""Initial tables

Revision ID: ada527385465
Revises: ee9bd4bb05ed
Create Date: 2026-03-19 16:57:36.606204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ada527385465'
down_revision: Union[str, Sequence[str], None] = 'ee9bd4bb05ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commission_evaluations', 'criteria_scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission_evaluations', sa.Column('criteria_scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
